[project]
authors = [{ name = "A.suzuki", email = "suzu.devworks@gmail.com" }]
dependencies = []
description = "Default template for PDM package"
license = { text = "MIT" }
name = "examples-web"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"


[tool.pdm]
distribution = false
